name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          sudo mkdir -p /home/ubuntu/app  # Ensure directory exists
          sudo cp -r $GITHUB_WORKSPACE/* /home/ubuntu/app/  # Copy contents, not the folder itself
          sudo chown -R ubuntu:ubuntu /home/ubuntu/app  # Ensure correct permissions

          cd /home/ubuntu/app  # Change directory to the deployed code
